FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", ImGui = "*", Bulkan = "*", "Bulkan.Utilities" = "*"}

[Project]
Name = "ImGuiImplVulkan"
DefaultNamespace = "ImGui"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../dist/$(Configuration)-$(Platform)/cimgui.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/../dist/$(Configuration)-$(Platform)/cimgui.lib"]
